CREATE OR REPLACE VIEW GADMAPPS.VW_AUTORIZACION_USUARIOS AS
SELECT
        U.ID_USUARIO,
        U.EMAIL,
        M.ID_MODULO,
        S.ID_SISTEMA,
        R.ID_ROL,
        S.NOMBRE AS SISTEMA,
        M.NOMBRE AS MODULO,
        R.NOMBRE AS ROL
FROM    GADMAPPS.RBAC_USUARIOS U
JOIN    GADMAPPS.RBAC_USUARIO_MODULO_ROL UMR   ON U.ID_USUARIO = UMR.ID_USUARIO
JOIN    GADMAPPS.RBAC_MODULOS M                ON UMR.ID_MODULO = M.ID_MODULO
JOIN    GADMAPPS.RBAC_SISTEMAS S               ON M.ID_SISTEMA = S.ID_SISTEMA
JOIN    GADMAPPS.RBAC_ROLES R                  ON UMR.ID_ROL = R.ID_ROL
WHERE   U.ESTADO = 'S'
AND     U.BLOQUEADO = 0
AND     UMR.ESTADO = 'S'
AND     M.ESTADO = 'S'
AND     S.ESTADO = 'S'
AND     R.ESTADO = 'S'
AND     (UMR.FECHA_INICIO IS NULL OR UMR.FECHA_INICIO <= TRUNC(SYSDATE))
AND     (UMR.FECHA_FIN IS NULL OR UMR.FECHA_FIN >= TRUNC(SYSDATE));