CREATE TABLE GADMAPPS.RBAC_SISTEMAS (
    ID_SISTEMA      NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE          VARCHAR2(150) NOT NULL,
    DESCRIPCION     VARCHAR2(255),
    URL_BASE        VARCHAR2(255),
    TOKEN_EXPIRACION_MIN NUMBER DEFAULT 60 NOT NULL,
    ESTADO          CHAR(1) DEFAULT 'S' NOT NULL,
    FEC_ING         DATE,
    FEC_MOD         DATE,

    CONSTRAINT PK_SISTEMAS PRIMARY KEY (ID_SISTEMA),
    CONSTRAINT UK_SISTEMA_NOMBRE UNIQUE (NOMBRE)
);


COMMENT ON COLUMN TKN_SISTEMAS.TOKEN_EXPIRACION_MIN IS 'Duracion del JWT en minutos (Ej: Bachillerato=7200 [5 dias], Pagos=15)';

SELECT * FROM GADMAPPS.RBAC_SISTEMAS;

CREATE TABLE GADMAPPS.RBAC_ROLES (
    ID_ROL          NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE          VARCHAR2(50) NOT NULL,
    DESCRIPCION     VARCHAR2(255),
    ESTADO          CHAR(1) DEFAULT 'S' NOT NULL,
    CONSTRAINT PK_ROLES PRIMARY KEY (ID_ROL),
    CONSTRAINT UK_ROL_NOMBRE UNIQUE (NOMBRE)
);

SELECT * FROM GADMAPPS.RBAC_ROLES;


CREATE TABLE GADMAPPS.RBAC_PERMISOS (
    ID_PERMISO      NUMBER GENERATED ALWAYS AS IDENTITY,
    NOMBRE          VARCHAR2(50) NOT NULL,
    ACCION          VARCHAR2(50) NOT NULL,
    ESTADO          CHAR(1) DEFAULT 'S' NOT NULL,
    CONSTRAINT PK_PERMISOS PRIMARY KEY (ID_PERMISO),
    CONSTRAINT UK_PERMISO_NOMBRE UNIQUE (NOMBRE)
);
COMMENT ON COLUMN GADMAPPS.RBAC_PERMISOS.ACCION IS 'CREATE, READ, UPDATE, DELETE, EXPORT, etc.';

SELECT * FROM GADMAPPS.RBAC_PERMISOS;


CREATE TABLE GADMAPPS.RBAC_MODULOS (
    ID_MODULO       NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_SISTEMA      NUMBER NOT NULL,
    NOMBRE          VARCHAR2(100) NOT NULL,
    DESCRIPCION     VARCHAR2(255),
    RUTA_BASE       VARCHAR2(255),
    ESTADO          CHAR(1) DEFAULT 'S' NOT NULL,
    FEC_ING         TIMESTAMP DEFAULT SYSTIMESTAMP,
    FEC_MOD         TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT PK_MODULOS PRIMARY KEY (ID_MODULO),
    CONSTRAINT FK_MODULO_SISTEMA FOREIGN KEY (ID_SISTEMA) REFERENCES GADMAPPS.RBAC_SISTEMAS(ID_SISTEMA),
    CONSTRAINT UK_MODULO_SISTEMA UNIQUE (ID_SISTEMA, NOMBRE)
);

SELECT * FROM GADMAPPS.RBAC_MODULOS;


CREATE TABLE GADMAPPS.RBAC_USUARIOS (
    ID_USUARIO        NUMBER GENERATED ALWAYS AS IDENTITY,
    TIPO_USUARIO      CHAR(1) DEFAULT 'C' NOT NULL, -- 'F': Funcionario, 'C': Ciudadano
    TIPO_DOCUMENTO    VARCHAR2(2) NOT NULL,         -- 'C': Cédula, 'R': RUC, 'P': Pasaporte
    NUM_DOCUMENTO     VARCHAR2(20) NOT NULL,        -- Alfanumérico por los pasaportes
    EMAIL             VARCHAR2(100) NOT NULL,
    PASSWORD_HASH     VARCHAR2(255) NOT NULL,
    NOMBRE            VARCHAR2(100) NOT NULL,       -- Obligatorio para auditoría
    APELLIDO          VARCHAR2(100) NOT NULL,       -- Obligatorio para auditoría
    ACTIVEDIRECTORY   CHAR(1) DEFAULT 'N' NOT NULL, -- 'S' o 'N'
    CODCABILDO        VARCHAR2(30) NULL,            -- Solo para funcionarios
    IDCABILDO         VARCHAR2(30) NULL,            -- Solo para funcionarios
    INTENTOS_FALLIDOS NUMBER DEFAULT 0 NOT NULL,
    BLOQUEADO         NUMBER(1) DEFAULT 0 NOT NULL,
    ULTIMO_ACCESO     TIMESTAMP WITH LOCAL TIME ZONE,
    CREADO_EN         TIMESTAMP WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ACTUALIZADO_EN    TIMESTAMP WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    ESTADO            CHAR(1) DEFAULT 'S' NOT NULL, -- 'S': Activo, 'N': Inactivo

    -- Restricciones (Constraints)
    CONSTRAINT PK_USUARIOS PRIMARY KEY (ID_USUARIO),
    CONSTRAINT UK_USUARIO_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UK_USUARIO_DOCUMENTO UNIQUE (TIPO_DOCUMENTO, NUM_DOCUMENTO), -- Evita duplicados
    CONSTRAINT CHK_USUARIO_BLOQUEADO CHECK (BLOQUEADO IN (0, 1)),
    CONSTRAINT CHK_TIPO_USUARIO CHECK (TIPO_USUARIO IN ('F', 'C')),
    CONSTRAINT CHK_TIPO_DOCUMENTO CHECK (TIPO_DOCUMENTO IN ('C', 'R', 'P')),
    CONSTRAINT CHK_ACT_DIRECTORY CHECK (ACTIVEDIRECTORY IN ('S', 'N'))
);

COMMENT ON COLUMN GADMAPPS.RBAC_USUARIOS.PASSWORD_HASH IS 'BCRYPT o ARGON2';
COMMENT ON COLUMN GADMAPPS.RBAC_USUARIOS.TIPO_USUARIO IS 'F = Funcionario Municipal, C = Ciudadano General';

SELECT * FROM GADMAPPS.RBAC_USUARIOS;


CREATE TABLE GADMAPPS.RBAC_ROL_PERMISOS (
    ID_ROL_PERMISO  NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_ROL          NUMBER NOT NULL,
    ID_PERMISO      NUMBER NOT NULL,
    FEC_ING       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_ROL_PERMISOS PRIMARY KEY (ID_ROL_PERMISO),
    CONSTRAINT FK_RP_ROL FOREIGN KEY (ID_ROL) REFERENCES GADMAPPS.RBAC_ROLES(ID_ROL) ON DELETE CASCADE,
    CONSTRAINT FK_RP_PERMISO FOREIGN KEY (ID_PERMISO) REFERENCES GADMAPPS.RBAC_PERMISOS(ID_PERMISO) ON DELETE CASCADE,
    CONSTRAINT UK_ROL_PERMISO UNIQUE (ID_ROL, ID_PERMISO)
);

SELECT * FROM GADMAPPS.RBAC_ROL_PERMISOS;


CREATE TABLE GADMAPPS.RBAC_USUARIO_MODULO_ROL (
    ID_UMR          NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_USUARIO      NUMBER NOT NULL,
    ID_MODULO       NUMBER NOT NULL,
    ID_ROL          NUMBER NOT NULL,
    ASIGNADO_POR    NUMBER,
    FECHA_INICIO    DATE,
    FECHA_FIN       DATE,
    ESTADO          CHAR(1) DEFAULT 'S' NOT NULL, -- 'S': Activo, 'N': Inactivo
    CREADO_EN       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_UMR PRIMARY KEY (ID_UMR),
    CONSTRAINT FK_UMR_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES GADMAPPS.RBAC_USUARIOS(ID_USUARIO),
    CONSTRAINT FK_UMR_MODULO FOREIGN KEY (ID_MODULO) REFERENCES GADMAPPS.RBAC_MODULOS(ID_MODULO),
    CONSTRAINT FK_UMR_ROL FOREIGN KEY (ID_ROL) REFERENCES GADMAPPS.RBAC_ROLES(ID_ROL),
    CONSTRAINT FK_UMR_ASIGNADOR FOREIGN KEY (ASIGNADO_POR) REFERENCES GADMAPPS.RBAC_USUARIOS(ID_USUARIO),
    CONSTRAINT UK_USUARIO_MODULO_ROL UNIQUE (ID_USUARIO, ID_MODULO, ID_ROL)
);

SELECT * FROM GADMAPPS.RBAC_USUARIO_MODULO_ROL;


CREATE TABLE GADMAPPS.RBAC_SESIONES (
    ID_SESION       NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_USUARIO      NUMBER NOT NULL,
    TOKEN_JTI       VARCHAR2(255) NOT NULL,
    IP_ORIGEN       VARCHAR2(45),
    USER_AGENT      VARCHAR2(500),
    CREADO_EN       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    EXPIRA_EN       TIMESTAMP WITH LOCAL TIME ZONE NOT NULL,
    REVOCADO        NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT PK_SESIONES PRIMARY KEY (ID_SESION),
    CONSTRAINT FK_SESION_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES GADMAPPS.RBAC_USUARIOS(ID_USUARIO),
    CONSTRAINT UK_TOKEN_JTI UNIQUE (TOKEN_JTI),
    CONSTRAINT CHK_SESION_REVOCADO CHECK (REVOCADO IN (0, 1))
);

SELECT * FROM GADMAPPS.RBAC_SESIONES;


CREATE TABLE GADMAPPS.RBAC_AUDITORIA (
    ID_AUDITORIA    NUMBER GENERATED ALWAYS AS IDENTITY,
    ID_USUARIO      NUMBER,
    ACCION          VARCHAR2(50) NOT NULL,
    TABLA_AFECTADA  VARCHAR2(100),
    ID_REGISTRO     NUMBER,
    VALOR_ANTERIOR  CLOB CONSTRAINT CHK_AUDIT_VAL_ANT_JSON CHECK (VALOR_ANTERIOR IS JSON OR VALOR_ANTERIOR IS NULL),
    VALOR_NUEVO     CLOB CONSTRAINT CHK_AUDIT_VAL_NUEV_JSON CHECK (VALOR_NUEVO IS JSON OR VALOR_NUEVO IS NULL),
    IP_ORIGEN       VARCHAR2(45),
    CREADO_EN       TIMESTAMP WITH LOCAL TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT PK_AUDITORIA PRIMARY KEY (ID_AUDITORIA),
    CONSTRAINT FK_AUDIT_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES GADMAPPS.RBAC_USUARIOS(ID_USUARIO) ON DELETE SET NULL
);

SELECT * FROM GADMAPPS.RBAC_AUDITORIA;


SELECT * FROM GADMAPPS.VW_FUNCIONARIOS;


